### ISSUE TITLE
Change Sound

### ISSUE THREAD

**Issue by NoBlueJeans** [SoaresPT/clue-scroll-notifier#1]
Would it be possible to add the ability to change the sound which plays when you get a clue scroll?

**Comment by SoaresPT** [comment]
Would you like the plugin to have its own directory and then you could replace the default sound file with whatever you'd like?

**Comment by NoBlueJeans** [comment]
That would be amazing! just like the C-Engineer plugin!

**Comment by SoaresPT** [comment]
@Danarlidge made an update that lets you set up your own custom sounds, as requested. Refer to the readme for instructions.
